name: data-getter

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: actions/data-grabber

jobs:
  get-weekly-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_PUBLIC_KEY: ${{ secrets.DB_PUBLIC_KEY}}
      - run: npm install
      - run: npm run build-action-data-grabber
      - run: npm run action-data-grabber