name: data-getter

on:
  workflow_dispatch:
  schedule:
    # Run at 12:00pm UTC (=8am EDT) every Thursday
    - cron: 0 12 * * 4
jobs:
  get-weekly-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: ./.github/actions/data-grabber
        name: Download Data
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_PUBLIC_KEY: ${{ secrets.DB_PUBLIC_KEY}}
