name: data-getter

on:
  workflow_dispatch:

defaults:
  run:
    working-direction: actions/data-grabber

jobs:
  get-weekly-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: node data-grabber.js